### ISSUE TITLE
Unable to compile...

### ISSUE THREAD

**Issue by roelschroeven** [saadware/protobuf-cppbuilder#1]
Hi,

I'm using C++Builder 2010, and I'm unsuccessfully trying to compile libprotobuf.

As far as I can see, a large issue is that Builder tries to compile files named *.cc as C source files instead of C++ source files. I tried renaming one file from *.cc to *.cpp, and that eliminated many errors (though not all).

Which version of C++Builder are you using to compile the project? Do you know of a way to tell Builder that *.cc files are C++, not C?

I want to thank you for the work you've done on this project, since it would be very useful to me (and probably many others) to use protocol buffers in Builder projects.

**Comment by roelschroeven** [comment]
Solved.

Typical: I had already been looking for it for a while, but now I find the solution, only minutes after reporting the issue.

It looks like I just had to set Setting Project / Options / C++ Compiler / Force C++ compile to true instead of false. I still can't compile, though; I'm looking into the next problem now.

**Comment by saadware** [comment]
Hi there. I'm sorry you're currently still having issues compiling. I know you mentioned that you were able to find the option to force C++ compile. I wanted to note that currently, the active projects are version C++Builder XE. I'm looking into ways on how to support multiple versions of C++Builder.

Please keep me posted on your progress. I'd be happy to help you get things going with this.

**Comment by roelschroeven** [comment]
Don't be sorry, it's hardly your fault :)

I also had to add $(BDS)\include and $(BDS)\include\dinkumware to the include path.

The next issue are errors while trying to instantiate scoped_ptr:

[BCC32 Error] common.h(454): E2450 Undefined structure 'DescriptorPool::Tables'
  Full parser context
    common.h(453): decision to instantiate:  ~scoped_ptrDescriptorPool::Tables::scoped_ptr()
    --- Resetting parser context for instantiation...
    importer.cc(47): #include ..\src\google/protobuf/compiler/importer.h
    importer.h(44): #include ..\src\google/protobuf/descriptor.h
    descriptor.h(59): #include ..\src\google/protobuf/stubs/common.h
    common.h(79): namespace google
    common.h(80): namespace protobuf
    common.h(423): namespace internal
    common.h(440): class scoped_ptr<C>
    common.h(453): parsing:  ~scoped_ptrDescriptorPool::Tables::scoped_ptr()

I tried with boost::scoped_ptr instead of the internal scoped_ptr, but that resulted in a similar error. Then I used boost::shared_ptr, and that seems to work: libprotobuf compiles now. I haven't had the time to check the other projects, and to test if everything not only builds but also works.

The change to boost::shared_ptr is not something I'm very happy about, but as far as I can see it should work.

**Comment by saadware** [comment]
Hi @rschroev,

Not that this makes the issue go away but I have this compiling on multiple machines, all of which are using C++Builder XE. You said you're using C++Builder 2010. I happen to have that version as well but I'm curious to know the method you used to convert the project files to 2010 compatible. 

Maybe together we can find a solution that solves the 2010 compile issue, as I don't think switching to the shared_ptr is ideal.

**Comment by roelschroeven** [comment]
Hi Scott,

It was actually very easy to "convert" the project files: not knowing which
version you use, I just tried to open them in. And that worked, without so
much as a warning.

As for the scoped_ptr: some methods, e.g. the destructor, have a line

```
enum { type_must_be_complete = sizeof(C) };
```

I tried using boost::scoped_ptr instead of the internal scoped_ptr, which
resulted in the same error. boost::scoped_ptr also has comparable code (in
checked_delete, which is called from scoped_ptr's destructor:

```
// intentionally complex - simplification causes regressions
typedef char type_must_be_complete[ sizeof(T)? 1: -1 ];
(void) sizeof(type_must_be_complete);
```

boost::shared_ptr does not have such code. So I think Builder 2010 wants the
full class definition available in common.h, which it doesn't have since it's
in descriptor.cc which common.h doesn't have access to.

Later today I'm going to write a program as small as possible still having
that problem, and which I can compile using Builder 2010, MSVC and gcc, to
confirm my suspicion. And hopefully we can find a solution that way.

Regards,
Roel

Scott Saad wrote:

> Hi @rschroev,
> 
> Not that this makes the issue go away but I have this compiling on multiple machines, all of which are using C++Builder XE. You said you're using C++Builder 2010. I happen to have that version as well but I'm curious to know the method you used to convert the project files to 2010 compatible. 
> 
> Maybe together we can find a solution that solves the 2010 compile issue, as I don't think switching to the shared_ptr is ideal.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/saadware/protobuf-cppbuilder/issues/1#issuecomment-2769541

## 

Doe vandaag eens iets levensbelangrijks: word stamceldonor.
Kijk op http://www.stamceldonor.be of http://www.infodonor.be

roel@roelschroeven.net
http://roelschroeven.net

**Comment by saadware** [comment]
Hi Roel,

Thanks again for trying this out. I would love for things to get working under the 2010 version of the compiler. Like I said, I do have this version as well but have not been able to test under it. I will attempt to do so hopefully later today and get back to you with my findings. (most likely just confirming what you've already found)

I've run across these types of errors with boost::scoped_ptr when working with partially defined classes (no constructor and destructor explicitly defined).

After I get my 2010 environment going, I'm hopeful we might be able to make some progress.

Take care,
Scott
